[database]
type = sqlite3
path = /var/lib/grafana/grafana.db
wal = true
cache_mode = shared

[feature_toggles]
enable = dashgpt

[security]
disable_initial_admin_creation = true

[user]
auto_assign_org_role = Viewer

[auth]
disable_login_form = true

[auth.jwt]
enabled = true
header_name = X-JWT-Assertion
username_claim = preferred_username
email_claim = email
role_attribute_path = role
auto_sign_up = true
allow_assign_grafana_admin = true
jwk_set_url = https://metadata.worker/jwks/v2.json
cache_ttl = 15m

[plugins]
# Pass SSL_CERT_FILE
forward_host_env_vars = grafana-llm-app

[metrics]
classic_http_histogram_enabled = false
